services:
  # バックエンドサービス
  - type: web
    name: pomohub-backend
    runtime: python
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        generateValue: true
      - key: DISCORD_WEBHOOK_URL
        sync: false
    disk:
      name: pomohub-data
      mountPath: /app/data
      sizeGB: 1

  # フロントエンドサービス  
  - type: static
    name: pomohub-frontend
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        sync: false